export const STACK_LIST = [
	"Stack A1",
	"Stack A2",
	"Stack A3",
	"Stack A4",
	"Stack A5",
	"Stack A6",
	"Stack A7",
	"Stack A8",
	"Stack A9",
	"Stack A10",
	"Stack B1",
	"Stack B2",
	"Stack B3",
	"Stack B4",
	"Stack B5",
	"Stack B6",
	"Stack B7",
	"Stack B8",
	"Stack B9",
	"Stack B10",
	"Stack C1",
	"Stack C2",
	"Stack C3",
	"Stack C4",
	"Stack C5",
	"Stack C6",
	"Stack C7",
	"Stack C8",
	"Stack C9",
	"Stack C10",
	"Stack D1",
	"Stack D2",
	"Stack D3",
	"Stack D4",
	"Stack D5",
	"Stack D6",
	"Stack D7",
	"Stack D8",
	"Stack D9",
	"Stack D10",
];
export const LGA_LIST = [
	"Akoko-Edo",
	"Egor",
	"Esan Central",
	"Esan North-East",
	"Esan South-East",
	"Esan West",
	"Etsako Central",
	"Etsako East",
	"Etsako West",
	"Igueben",
	"Ikpoba-Okha",
	"Oredo",
	"Orhionmwon",
	"Ovia North-East",
	"Ovia South-West",
	"Owan East",
	"Owan West",
	"Uhunmwonde",
];
export const BUILDING_STATUS = ["Proposed", "Under Construction", "Built"];
export const BUILDING_TYPE = [
	"Commercial",
	"Residential",
	"Mixed",
	"Religious",
	"Educational",
	"Industrial",
	"Recreational",
];
export const TASK_LIST = [
	"MINUTE PLAN",
	"UPDATE PLAN",
	"COMMENT ON PLAN",
	"GENERATE PLAN NUMBER",
	"CREATE PLAN",
	"CREATE BILL",
	"VET PLAN",
	"EXPORT DATA",
];

export const COMMENT_STATUS_LIST = [
	"Action Taken",
	"Observation",
	"Issue Raised",
	"Pending Action",
	"Calls",
	"Request Sent",
	"Request Received",
	"Correction",
	"Inspection",
	"Site visit",
];

export const MINUTE_STATUS_LIST = [
	"Process Further",
	"Plan In Order",
	"Issue Raised",
	"Recommended for Approval",
	"Recommended for Rejection",
	"Issuance of Conveyance",
	"KIV",
	"Approved",
];
export const VETTING_STATUS_LIST = [
	"Cleared",
	"Issue Raised",
	"Process Further",
];
export const JOB_TITLE_LIST = [
	"Architect",
	"Civil Engineer",
	"Mechanical Engineer",
	"Electrical Engineer",
	"Town Planning Officer",
	"Estate Surveyor",
	"Quantity Surveyor",
	"ICTA",
];
export const POSITION_LIST = [
	"Hon. Commissioner",
	"Perm. Secretary",
	"Director",
	"APO",
	"STPO",
	"TPO",
	"TA",
	"ICTA",
	"ESV",
	"QS",
	"Staff",
];
export const FEEDBACK_LIST = [
	"Product Feedback",
	"Feature Requests",
	"Bug / Issue Reports",
	"Complaints & Questions",
	"Praise & Appreciation",
];

export const ASSESSMENT_FEES = {
	fastTrackFee: 100000,
	registrationFee: 25000,
	developmentFee: 50000,
	squareMeterFeeList: [25, 50, 75, 100],
	facilities: [
		{
			name: "Gate House",
			amount: 50000,
		},
		{
			name: "Fence",
			amount: 100000,
		},
	],
	others: [
		{
			name: "Land Use",
			amount: 50000,
		},
		{
			name: "Tax",
			amount: 100000,
		},
	],
};

export const APPLICATION_DOCUMENTS = [
	{ tag: "survey", name: "Survey plan" },
	{ tag: "layout", name: "Layout plan" },
	{ tag: "deed", name: "Deed of Transfer" },
	{ tag: "obaApproval", name: "Oba approval" },
	{ tag: "cOfO", name: "Certificate of occupancy" },
	{ tag: "sar", name: "Site analysis report" },
	{ tag: "soilTest", name: "Soil Test" },
	{ tag: "eia", name: "Environmental impact analysis" },
	{ tag: "fireSafety", name: "Fire safety report" },
	{ tag: "tax", name: "Tax clearance" },
	{ tag: "mechanical", name: "Mechanical Drawing" },
	{ tag: "electrical", name: "Electrical Drawing" },
	{ tag: "architecture", name: "Architectural Drawing" },
	{ tag: "structural", name: "Structural Drawing" },
];
